AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Layout/DotPosition:
  EnforcedStyle: leading

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/mail-ses.rb'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact
